import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Builder from '../src/components/Builder'
import { Container } from '@mui/material'

export default function Home() {

  return <div>
    <Head>
      <title>Code generator</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <Container>
        <Builder />
      </Container>
    </main>
  </div>
}